
- alias: "Turn on toilet path at night"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_upstairs_hall_motion
      to: 'on'
  condition: 
    - condition: time
      after: "23:00"
      before: "05:30"
  action:
    - service: script.timed_toilet_path_on

- alias: Night Time
  trigger:
    platform: time
    after: "23:00"
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.night_time

- alias: Day Time
  trigger:
    platform: time
    after: "05:00"
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.night_time

- alias: Turn Normal Mode Off
  trigger:
    - platform: state
      entity_id: input_boolean.night_time
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: input_boolean.party_time
      from: 'off'
      to: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.normal_mode

- alias: Turn Normal Mode On
  trigger:
    - platform: state
      entity_id: input_boolean.night_time
      from: 'on'
      to: 'off'
    - platform: state
      entity_id: input_boolean.party_time
      from: 'on'
      to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.party_time
        state: 'off'
      - condition: state
        entity_id: input_boolean.night_time
        state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.normal_mode
