
#########################################################
# Upstairs Hall Motion Sensor
#########################################################

- platform: mqtt
  name: "motion_upstairs_hall_motion"
  state_topic: "smartthings/Upstairs Hall Motion/motion"
  payload_on: "active"
  payload_off: "inactive"

#########################################################
# Stairs Motion Sensor
#########################################################

- platform: mqtt
  name: "motion_stairs_motion"
  state_topic: "smartthings/Stairs Motion/motion"
  payload_on: "active"
  payload_off: "inactive"

#########################################################
# Downstairs Hall Motion Sensor
#########################################################

- platform: mqtt
  name: "motion_downstairs_hall_motion"
  state_topic: "smartthings/Downstairs Hall Motion/motion"
  payload_on: "active"
  payload_off: "inactive"

#########################################################
# Living Room Motion Sensor
#########################################################

- platform: mqtt
  name: "multisensor_living_room_motion"
  state_topic: "smartthings/Living Room Multisensor/motion"
  payload_on: "active"
  payload_off: "inactive"

- platform: mqtt
  name: "motion_living_room_motion"
  state_topic: "smartthings/Living Room Motion/motion"
  payload_on: "active"
  payload_off: "inactive"

#########################################################
# Kitchen Motion Sensor
#########################################################

- platform: mqtt
  name: "multisensor_kitchen_motion"
  state_topic: "smartthings/Kitchen Multisensor/motion"
  payload_on: "active"
  payload_off: "inactive"

#########################################################
# Dining Room Motion Sensor
#########################################################

- platform: mqtt
  name: "motion_dining_room_motion"
  state_topic: "smartthings/Dining Room Motion/motion"
  payload_on: "active"
  payload_off: "inactive"

#########################################################
# Office Motion Sensor
#########################################################

- platform: mqtt
  name: "motion_office_motion"
  state_topic: "smartthings/Office Motion/motion"
  payload_on: "active"
  payload_off: "inactive"

#########################################################
# Doorbell
#########################################################

- platform: mqtt
  name: "dash_front_door_button"
  state_topic: "dash/doorbell/button"
  payload_on: "on"
  payload_off: "off"
