#########################################################
# Upstairs Hall Motion Sensor
#########################################################

- platform: mqtt
  name: "motion_upstairs_hall_battery"
  state_topic: "smartthings/Upstairs Hall Motion/battery"
  unit_of_measurement: "%"
  
- platform: mqtt
  name: "motion_upstairs_hall_temperature"
  state_topic: "smartthings/Upstairs Hall Motion/temperature"
  unit_of_measurement: "°C"

#########################################################
# Stairs Motion Sensor
#########################################################

- platform: mqtt
  name: "motion_stairs_battery"
  state_topic: "smartthings/Stairs Motion/battery"
  unit_of_measurement: "%"
  
- platform: mqtt
  name: "motion_stairs_temperature"
  state_topic: "smartthings/Stairs Motion/temperature"
  unit_of_measurement: "°C"

#########################################################
# Downstairs Hall Motion Sensor
#########################################################

- platform: mqtt
  name: "motion_downstairs_hall_battery"
  state_topic: "smartthings/Downstairs Hall Motion/battery"
  unit_of_measurement: "%"

- platform: mqtt
  name: "motion_downstairs_hall_temperature"
  state_topic: "smartthings/Downstairs Hall Motion/temperature"
  unit_of_measurement: "°C"

#########################################################
# Living Room Motion Sensor
#########################################################

- platform: mqtt
  name: "motion_living_room_battery"
  state_topic: "smartthings/Living Room Motion/battery"
  unit_of_measurement: "%"
  
- platform: mqtt
  name: "motion_living_room_temperature"
  state_topic: "smartthings/Living Room Motion/temperature"
  unit_of_measurement: "°C"

#########################################################
# Kitchen Motion Sensor
#########################################################

- platform: mqtt
  name: "motion_kitchen_battery"
  state_topic: "smartthings/Kitchen Motion/battery"
  unit_of_measurement: "%"
  
- platform: mqtt
  name: "motion_kitchen_temperature"
  state_topic: "smartthings/Kitchen Motion/temperature"
  unit_of_measurement: "°C"

#########################################################
# Dining Room Motion Sensor
#########################################################

- platform: mqtt
  name: "motion_dining_room_battery"
  state_topic: "smartthings/Dining Room Motion/battery"
  unit_of_measurement: "%"
  
- platform: mqtt
  name: "motion_dining_room_temperature"
  state_topic: "smartthings/Dining Room Motion/temperature"
  unit_of_measurement: "°C"

#########################################################
# Lounge Lamp Power Switch
#########################################################

- platform: mqtt
  name: "switch_living_room_lamp_power"
  state_topic: "smartthings/Living Room Lamp/power"
  unit_of_measurement: "W"
